/*!
@file CValueProvider.h
@author Anthony L., Loïck M., Thomas M., Floran N., Loïc P.
@date 08/12/2014
@version  1.0
*/
#pragma once

#include "CTestClass.h"
#include <vector>
#include <limits>

namespace nsTests
{
    /*!
        @brief Generates random int between min and max.
                Be careful to seed the random generator.
     */
    int rand (int min, int max)
    {
        return min + (std::rand () % (max - min + 1));
    }

    // C++11 c'est bon, mangez-en.
    /*!
        @brief A type that conceptually represents a simple data collection, underlying implementation is not pertinent.
                Just need iterators and operator[].
                std::vector was best suited for the task, but could be replaced by anything...
     */
    template<typename T> using CCollection = std::vector<T>;

    /*!
        @brief CValueProvider provides semi-random values for tested classes...
     */
    template<typename T>
    class CValueProvider
    {
    public:
        CCollection<T> operator() (const int /*valueCount*/ = 0)
        {
            // typeid(T).name() only gives mangled class name, not very clear but still a good indication.
            throw std::runtime_error (std::string ("Value provider for type ") + typeid (T).name () + " does not exist.");
        }
    };

    /*!
        @brief Pointerize values of type T generated by CValueProvider<T>.
     */
    template<typename T>
    class CValueProvider<T *>
    {
    public:
        CCollection<T *> operator() (const int valueCount = 0)
        {
            CCollection<T> array = CValueProvider<T> () (valueCount);
            CCollection<T *> ptrArray;
            ptrArray.reserve (array.size ());

            for (T x : array)
                ptrArray.push_back (new T (x));

            return ptrArray;
        }
    };

    /*!
        @brief Shared pointerize values of type T generated by CValueProvider<T>.
     */
    template<typename T>
    class CValueProvider<std::shared_ptr<T>>
    {
    public:
        CCollection<std::shared_ptr<T>> operator() (const int valueCount = 0)
        {
            CCollection<T> array = CValueProvider<T> () (valueCount);
            CCollection<std::shared_ptr<T>> ptrArray;
            ptrArray.reserve (array.size ());

            for (T x : array)
                ptrArray.push_back (std::make_shared<T> (x));

            return ptrArray;
        }
    };

    /*!
        @brief Generate random test values for int.
     */
    template<>
    class CValueProvider<int>
    {
    public:
        CCollection<int> operator() (const int valueCount = 0) noexcept
        {
            int arraySize = valueCount ? valueCount : rand (10, 100);

            CCollection<int> array (arraySize);

            array[0] = 0;
            array[1] = std::numeric_limits<int>::max ();
            array[2] = std::numeric_limits<int>::min ();

            for (int i = 3; i < arraySize; ++i)
                array[i] = std::rand ();

            return array;
        }
    };

    /*!
        @brief Generate random test value for TestClass.
     */
    template<>
    class CValueProvider<TestClass>
    {
    public:
        CCollection<TestClass> operator() (const int valueCount = 0) noexcept
        {
            int arraySize = valueCount ? valueCount : rand (10, 100);
            CCollection<TestClass> array;
            array.reserve (arraySize);

            array.push_back (TestClass (4654, "MARQUE LA PORTE"));

            for (int i = array.size (); i < arraySize; ++i)
            {
                std::string name;
                for (int j = 0; j < rand (10, 20); ++j)
                    name += static_cast<char>(rand (66, 89));

                array.push_back (TestClass (rand (0, 30), name));
            }

            return array;
        }
    };
}
